apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}-core
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ipFamilyPolicy: {{ if eq (len .Values.service.ipFamilies) 2 }}PreferDualStack{{ else }}SingleStack{{ end }}
  ports:
    - port: {{ .Values.service.corePort }}
      targetPort: 3001
      protocol: TCP
      name: core
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logto
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}-admin
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ipFamilyPolicy: {{ if eq (len .Values.service.ipFamilies) 2 }}PreferDualStack{{ else }}SingleStack{{ end }}
  ports:
    - port: {{ .Values.service.adminPort }}
      targetPort: 3002
      protocol: TCP
      name: admin
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logto
