{{- if .Values.n8n.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
  labels:
    app: {{ .Release.Name }}
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.n8n.gateway.sectionName }}-gateway
      namespace: default
  hostnames:
    - {{ .Values.n8n.gateway.hostname }}
  rules:
    - matches:
        - path:
            type: {{ .Values.n8n.gateway.pathType }}
            value: {{ .Values.n8n.gateway.path }}
      backendRefs:
        - name: {{ .Values.n8n.gateway.serviceName | default .Release.Name }}
          port: {{ .Values.n8n.gateway.servicePort | default .Values.n8n.service.port }}
{{- end }}