{{- if and .Values.n8n.persistence.enabled (not .Values.n8n.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ .Release.Name }}
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.n8n.persistence.accessMode }}
  {{- if .Values.n8n.persistence.storageClass }}
  storageClassName: {{ .Values.n8n.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.n8n.persistence.size }}
{{- end }}