apiVersion: v1
kind: Secret
metadata:
  name: n8n-encryption-key
  labels:
    app: {{ .Release.Name }}
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryptionKey: "{{ randAlphaNum 24 }}"
